CREATE TABLE [dbo].[AGENT_ORC_HIERARCHY] (
    [AGN_SHT_DESC]     VARCHAR (50) NULL,
    [ORC_AGN_SHT_DESC] VARCHAR (50) NULL,
    [HIERARCHY_TYPE]   VARCHAR (50) NULL,
    [APPLY_ORC_FLAG]   VARCHAR (1)  NULL
);


GO

