CREATE TABLE [dbo].[CPC_PROPOSAL_FORM_TRAD_OTHER_INSURER_DETAILS] (
    [CPF_CPP_REF_NBR]        VARCHAR (50)    NULL,
    [CPF_PPCT_TYPE_CODE]     VARCHAR (50)    NULL,
    [HAS_OTHER_INSURER]      VARCHAR (50)    NULL,
    [INSURER_NAME]           VARCHAR (150)   NULL,
    [SUM_ASSURED]            NUMERIC (18, 2) NULL,
    [PRIOR_PROPOSAL_DECLINE] VARCHAR (50)    NULL,
    [DECLINE_REASON]         VARCHAR (4000)  NULL,
    [CREATE_DATE]            DATETIME        NULL,
    [CREATE_USER]            VARCHAR (150)   NULL,
    [LAST_MODIFIED_DATE]     DATETIME        NULL,
    [LAST_MODIFIED_USER]     VARCHAR (150)   NULL
);


GO

