CREATE TABLE [dbo].[CPC_PROPOSAL_FORM_TRAD_MORTGAGE_INFO] (
    [CPF_CPP_REF_NBR]        VARCHAR (50)   NULL,
    [CPF_PPCT_TYPE_CODE]     VARCHAR (50)   NULL,
    [NAME_OF_INSTITUTION]    VARCHAR (50)   NULL,
    [ADDRESS_OF_INSTITUTION] VARCHAR (150)  NULL,
    [INTEREST_RATE]          NUMERIC (5, 2) NULL,
    [CREATE_DATE]            DATETIME       NULL,
    [CREATE_USER]            VARCHAR (150)  NULL,
    [LAST_MODIFIED_DATE]     DATETIME       NULL,
    [LAST_MODIFIED_USER]     VARCHAR (150)  NULL
);


GO

