CREATE TABLE [dbo].[CPC_PROPOSAL_PACK_CONTENT_TYPES] (
    [PPCT_TYPE_CODE]   VARCHAR (50)  NULL,
    [PPCT_SHT_DESC]    VARCHAR (50)  NULL,
    [PPCT_DESC]        VARCHAR (150) NULL,
    [PPCT_CREATE_DATE] DATETIME      NULL,
    [PPCT_CREATE_USER] VARCHAR (150) NULL,
    [PPCT_CLASS_CODE]  VARCHAR (50)  NULL,
    [PPCT_CLASS_DESC]  VARCHAR (150) NULL
);


GO

