CREATE TABLE [dbo].[CPC_PROPOSAL_FORM_TRAD_MEDICAL_HISTORY] (
    [CPF_CPP_REF_NBR]    VARCHAR (50)    NULL,
    [CPF_PPCT_TYPE_CODE] VARCHAR (50)    NULL,
    [HOSPITAL_NAME]      VARCHAR (150)   NULL,
    [HOSPITAL_ADDRESS]   VARCHAR (250)   NULL,
    [HEIGHT_IN_METERS]   NUMERIC (18, 2) NULL,
    [WEIGHT_IN_KG]       NUMERIC (18, 2) NULL,
    [CREATE_DATE]        DATETIME        NULL,
    [CREATE_USER]        VARCHAR (150)   NULL,
    [LAST_MODIFIED_DATE] DATETIME        NULL,
    [LAST_MODIFIED_USER] VARCHAR (150)   NULL
);


GO

