CREATE TABLE [dbo].[CPC_PROPOSAL_FORM_TRAD_DIGITAL_PLAN_NOMINEES] (
    [CPF_CPP_REF_NBR]     VARCHAR (50)    NULL,
    [CPF_PPCT_TYPE_CODE]  VARCHAR (50)    NULL,
    [NOMINEE_NAME]        VARCHAR (150)   NULL,
    [NOMINEE_DOB]         DATE            NULL,
    [RELATIONSHIP]        VARCHAR (50)    NULL,
    [NOMINEE_SUM_ASSURED] NUMERIC (18, 2) NULL,
    [CREATE_DATE]         DATETIME        NULL,
    [CREATE_USER]         VARCHAR (150)   NULL,
    [LAST_MODIFIED_DATE]  DATETIME        NULL,
    [LAST_MODIFIED_USER]  VARCHAR (150)   NULL
);


GO

