CREATE TABLE [dbo].[CPC_BRANCHES] (
    [ROW_ID]            INT           IDENTITY (1, 1) NOT NULL,
    [SRC_SYSTEM_CODE]   VARCHAR (50)  NULL,
    [LOCAL_SYSTEM_CODE] VARCHAR (50)  NULL,
    [BRANCH_NAME]       VARCHAR (150) NULL,
    [BRANCH_EMAIL]      VARCHAR (150) NULL
);


GO

