CREATE TABLE [dbo].[CPC_PROPOSAL_FORM_TRAD_CHILDREN_EDUCATION] (
    [CPF_CPP_REF_NBR]      VARCHAR (50)    NULL,
    [CPF_PPCT_TYPE_CODE]   VARCHAR (50)    NULL,
    [SCHOOL_FEES_PER_TERM] NUMERIC (18, 2) NULL,
    [BENEFIT_PCT]          NUMERIC (5, 2)  NULL,
    [CREATE_DATE]          DATETIME        NULL,
    [CREATE_USER]          VARCHAR (150)   NULL,
    [LAST_MODIFIED_DATE]   DATETIME        NULL,
    [LAST_MODIFIED_USER]   VARCHAR (150)   NULL
);


GO

