CREATE TABLE [dbo].[CPC_PROPOSAL_PACK_STATUS_LOG] (
    [CPP_REF_NBR]       VARCHAR (50)  NULL,
    [STATUS_DESC]       VARCHAR (50)  NULL,
    [FROM_DATE]         DATE          NULL,
    [TO_DATE]           DATE          NULL,
    [CREATE_DATE_STAMP] DATETIME      NULL,
    [CREATE_USER]       VARCHAR (150) NULL
);


GO

