CREATE TABLE [dbo].[CPC_PROPOSAL_PACKS_TYPE] (
    [TYPE_CODE]             VARCHAR (50)  NULL,
    [TYPE_CODE_DESCRIPTION] VARCHAR (150) NULL,
    [CREATE_DATE]           DATETIME      NULL,
    [CREATE_USER]           VARCHAR (150) NULL
);


GO

