CREATE TABLE [dbo].[CPC_PROPOSAL_PACKS_FORMS] (
    [PROPOSAL_PACK_TYPE] VARCHAR (50)  NULL,
    [PPCT_SHT_DESC]      VARCHAR (50)  NULL,
    [CREATE_DATE]        DATETIME      NULL,
    [CREATE_USER]        VARCHAR (150) NULL
);


GO

