CREATE TABLE [dbo].[CPC_REF_TYPES] (
    [REF_TYPE_CODE] VARCHAR (50)  NULL,
    [REF_TYPE_DESC] VARCHAR (150) NULL,
    [CREATE_DATE]   DATETIME      NULL,
    [CREATE_USER]   VARCHAR (150) NULL
);


GO

