CREATE TABLE [dbo].[CPC_PROPOSAL_FORM_TRAD_GENERAL] (
    [CPF_CPP_REF_NBR]       VARCHAR (50)  NULL,
    [CPF_PPCT_TYPE_CODE]    VARCHAR (50)  NULL,
    [SALUTATION_TITLE_CODE] VARCHAR (50)  NULL,
    [SALUTATION_OTHERS]     VARCHAR (50)  NULL,
    [PRODUCT_CODE]          VARCHAR (50)  NULL,
    [FIRST_NAME]            VARCHAR (150) NULL,
    [MIDDLE_NAME]           VARCHAR (150) NULL,
    [SURNAME]               VARCHAR (150) NULL,
    [DATE_OF_BIRTH]         DATE          NULL,
    [GENDER]                VARCHAR (50)  NULL,
    [GENDER_OTHERS]         VARCHAR (50)  NULL,
    [STATE_OF_ORIGIN_CODE]  VARCHAR (50)  NULL,
    [NATIONALITY_CODE]      VARCHAR (50)  NULL,
    [COUNTRY_OF_ORIGIN]     VARCHAR (50)  NULL,
    [TOWN_OR_CITY_OF_BIRTH] VARCHAR (50)  NULL,
    [COUNTRY_OF_BIRTH]      VARCHAR (50)  NULL,
    [RESIDENTIAL_ADDRESS]   VARCHAR (150) NULL,
    [ADDRESS_TOWN]          VARCHAR (50)  NULL,
    [ADDRESS_CITY]          VARCHAR (50)  NULL,
    [ADDRESS_STATE]         VARCHAR (50)  NULL,
    [ADDRESS_COUNTRY]       VARCHAR (50)  NULL,
    [CREATE_DATE]           DATETIME      NULL,
    [CREATE_USER]           VARCHAR (150) NULL,
    [LAST_MODIFIED_DATE]    DATETIME      NULL,
    [LAST_MODIFIED_USER]    VARCHAR (150) NULL
);


GO

