CREATE TABLE [dbo].[CPC_PROPOSAL_FORM_TRAD_BANK_INFO] (
    [CPF_CPP_REF_NBR]    VARCHAR (50)  NULL,
    [CPF_PPCT_TYPE_CODE] VARCHAR (50)  NULL,
    [BANK_NAME]          VARCHAR (50)  NULL,
    [ACCOUNT_NUMBER]     VARCHAR (50)  NULL,
    [ACCOUNT_NAME]       VARCHAR (150) NULL,
    [BVN]                VARCHAR (50)  NULL,
    [BANK_PRODUCT_NAME]  VARCHAR (50)  NULL,
    [CREATE_DATE]        DATETIME      NULL,
    [CREATE_USER]        VARCHAR (150) NULL,
    [LAST_MODIFIED_DATE] DATETIME      NULL,
    [LAST_MODIFIED_USER] VARCHAR (150) NULL
);


GO

