CREATE TABLE [dbo].[CPC_REF_TYPES_CODE] (
    [REF_TYPE_CODE]          VARCHAR (50)  NULL,
    [REF_TYPE_REF_CODE]      VARCHAR (50)  NULL,
    [REF_TYPE_REF_CODE_DESC] VARCHAR (150) NULL,
    [CREATE_DATE]            DATETIME      NULL,
    [CREATE_USER]            VARCHAR (150) NULL
);


GO

