CREATE TABLE [dbo].[ENDOWMENT_COMM] (
    [OPRI_CODE]                 NUMERIC (15)    NULL,
    [OPRI_LTR_TRANS_NO]         NUMERIC (22)    NULL,
    [OPRI_AMT]                  NUMERIC (23, 5) NULL,
    [OPRI_INSTLMT_NO]           NUMERIC (10)    NULL,
    [OPRI_POL_CODE]             NUMERIC (15)    NULL,
    [OPRI_POL_POLICY_NO]        VARCHAR (100)   NULL,
    [OPRI_COMM_RATE]            NUMERIC (10, 5) NULL,
    [OPRI_COMM_AMT]             NUMERIC (23, 5) NULL,
    [OPRI_AGEN_CODE]            NUMERIC (15)    NULL,
    [OPRI_AUTHORISED]           VARCHAR (5)     NULL,
    [OPRI_AUTHORISED_BY]        VARCHAR (20)    NULL,
    [OPRI_PAID_TO_DATE]         VARCHAR (50)    NULL,
    [OPRI_PA_ALLOC_POSTED_DATE] VARCHAR (50)    NULL,
    [OPRI_DATE]                 VARCHAR (50)    NULL,
    [OPRI_COMM_PAID]            VARCHAR (3)     NULL,
    [OPRI_COMM_PAID_DATE]       VARCHAR (50)    NULL,
    [OPRI_COP_CODE]             NUMERIC (15)    NULL,
    [OPRI_PAY_TRANS_NO]         NUMERIC (22)    NULL,
    [OPRI_WHDTAX_RATE]          NUMERIC (10, 5) NULL,
    [OPRI_WHDTAX_AMT]           NUMERIC (23, 5) NULL,
    [OPRI_OPR_RECEIPT_NO]       VARCHAR (100)   NULL,
    [OPRI_OPR_RECEIPT_DATE]     VARCHAR (50)    NULL,
    [OPRI_DRCR]                 VARCHAR (1)     NULL,
    [OPRI_BRN_CODE]             NUMERIC (15)    NULL,
    [OPRI_UNT_OVCOM_RATE]       NUMERIC (23, 5) NULL,
    [OPRI_UNT_OVCOM_AMT]        NUMERIC (23, 5) NULL,
    [OPRI_UNT_AGEN_CODE]        NUMERIC (15)    NULL,
    [OPRI_BRN_OVCOM_RATE]       NUMERIC (23, 5) NULL,
    [OPRI_BRN_OVCOM_AMT]        NUMERIC (23, 5) NULL,
    [OPRI_BRN_AGEN_CODE]        NUMERIC (15)    NULL,
    [OPRI_RGN_OVCOM_RATE]       NUMERIC (23, 5) NULL,
    [OPRI_RGN_OVCOM_AMT]        NUMERIC (23, 5) NULL,
    [OPRI_RGN_AGEN_CODE]        NUMERIC (15)    NULL,
    [OPRI_REV_INSTLMT_NO]       NUMERIC (10)    NULL,
    [OPRI_BRA_OVCOM_RATE]       NUMERIC (23, 5) NULL,
    [OPRI_BRA_OVCOM_AMT]        NUMERIC (23, 5) NULL,
    [OPRI_BRA_AGEN_CODE]        NUMERIC (15)    NULL,
    [PRODUCT]                   VARCHAR (200)   NULL,
    [PROD_CODE]                 VARCHAR (50)    NULL
);


GO

