CREATE TABLE [dbo].[ORC_SCENARIO_RATE] (
    [SCENARIO_ID]  VARCHAR (50) NULL,
    [PRODUCT_TYPE] VARCHAR (50) NULL,
    [ORC_POSITION] VARCHAR (50) NULL,
    [ORC_RATE]     FLOAT (53)   NULL
);


GO

