CREATE TABLE [dbo].[TQ_POLICIES] (
    [AGN_CODE]        VARCHAR (50) NULL,
    [POLICY_NO]       VARCHAR (50) NULL,
    [POL_PROPOSAL_NO] VARCHAR (50) NULL,
    [AGENT_SHT_DESC]  VARCHAR (50) NULL,
    [PROD_CODE]       VARCHAR (50) NULL,
    [POLICY_STATUS]   VARCHAR (50) NULL
);


GO

