CREATE TYPE [dbo].[UDT_CPC_FORM_TRAD_BANK_INFO] AS TABLE (
    [CPF_CPP_REF_NBR]    VARCHAR (50)  NULL,
    [CPF_PPCT_TYPE_CODE] VARCHAR (50)  NULL,
    [BANK_NAME]          VARCHAR (50)  NULL,
    [ACCOUNT_NUMBER]     VARCHAR (50)  NULL,
    [ACCOUNT_NAME]       VARCHAR (150) NULL,
    [BVN]                VARCHAR (50)  NULL,
    [BANK_PRODUCT_NAME]  VARCHAR (50)  NULL);


GO

