CREATE TYPE [dbo].[UDT_CPC_FORM_TRAD_OTHER_MEDICAL_INFO] AS TABLE (
    [CPF_CPP_REF_NBR]        VARCHAR (50)  NULL,
    [CPF_PPCT_TYPE_CODE]     VARCHAR (50)  NULL,
    [SKIN_DISORDER]          VARCHAR (50)  NULL,
    [NIGHT_SWEATS]           VARCHAR (50)  NULL,
    [WEIGHT_LOSS]            VARCHAR (50)  NULL,
    [SWOLLEN_GLANDS]         VARCHAR (50)  NULL,
    [RECURRENT_DIARRHEA]     VARCHAR (50)  NULL,
    [HEPATITIS_B]            VARCHAR (50)  NULL,
    [HIV_AIDS]               VARCHAR (50)  NULL,
    [BLOOD_TRANSFUSION]      VARCHAR (50)  NULL,
    [PAST_TIME_ACTIVITIES]   VARCHAR (250) NULL,
    [RESIDE_OUTSIDE_NIGERIA] VARCHAR (50)  NULL);


GO

