CREATE TYPE [dbo].[UDT_CPC_FORM_TRAD_TAX_INFO] AS TABLE (
    [CPF_CPP_REF_NBR]      VARCHAR (50)  NULL,
    [CPF_PPCT_TYPE_CODE]   VARCHAR (50)  NULL,
    [TIN]                  VARCHAR (50)  NULL,
    [EMPLOYER_NAME]        VARCHAR (150) NULL,
    [EMPLOYER_ADDRESS]     VARCHAR (150) NULL,
    [EMPLOYER_EMAIL]       VARCHAR (150) NULL,
    [EMPLOYER_PHONE_NBR]   VARCHAR (150) NULL,
    [CUST_RELIGION]        VARCHAR (50)  NULL,
    [CUST_OCCUPATION]      VARCHAR (150) NULL,
    [CUST_SOURCE_OF_FUNDS] VARCHAR (150) NULL);


GO

