CREATE TYPE [dbo].[UDT_CPC_FORM_TRAD_SUM_ASSURED] AS TABLE (
    [CPF_CPP_REF_NBR]    VARCHAR (50)    NULL,
    [CPF_PPCT_TYPE_CODE] VARCHAR (50)    NULL,
    [SUM_ASSURED]        NUMERIC (18, 2) NULL,
    [TERM_YEAR]          INT             NULL,
    [FIRST_PREMIUM_PAID] NUMERIC (18, 2) NULL,
    [REGULAR_PREMIUM]    NUMERIC (18, 2) NULL,
    [PAYMENT_FREQUENCY]  VARCHAR (50)    NULL,
    [FROM_DATE]          VARCHAR (50)    NULL,
    [MATURIRY_DATE]      VARCHAR (50)    NULL,
    [PAYMENT_MODE]       VARCHAR (50)    NULL);


GO

