CREATE TYPE [dbo].[UDT_CPC_FORM_TRAD_DIGITAL_PLAN] AS TABLE (
    [CPF_CPP_REF_NBR]     VARCHAR (50)    NULL,
    [CPF_PPCT_TYPE_CODE]  VARCHAR (50)    NULL,
    [NOMINEE_NAME]        VARCHAR (150)   NULL,
    [NOMINEE_DOB]         VARCHAR (15)    NULL,
    [RELATIONSHIP]        VARCHAR (50)    NULL,
    [NOMINEE_SUM_ASSURED] NUMERIC (18, 2) NULL);


GO

