CREATE TABLE [SRC].[TQC_AGENCIES] (
    [AGN_CODE]     VARCHAR (50)  NULL,
    [AGN_SHT_DESC] VARCHAR (50)  NULL,
    [AGN_NAME]     VARCHAR (150) NULL,
    [AGN_STATUS]   VARCHAR (50)  NULL,
    [AGN_ACT_CODE] INT           NULL
);


GO

