CREATE procedure dbo.CPC_ADD_UPDATE_PROPOSAL_FORM_TRAD_IDENTIFICATION (
	@caller varchar(150),
	@data dbo.UDT_CPC_FORM_TRAD_IDENTITY readonly
)
as
begin
	set nocount on;

	merge dbo.CPC_PROPOSAL_FORM_TRAD_IDENTITY as t
	using @data as s on (
		t.CPF_CPP_REF_NBR = s.CPF_CPP_REF_NBR
		and t.CPF_PPCT_TYPE_CODE = s.CPF_PPCT_TYPE_CODE
	)
	when matched then update set
		MEANS_OF_IDENTIFICATION = s.MEANS_OF_IDENTIFICATION,
		MEANS_OF_IDENTIFICATION_OTHERS = s.MEANS_OF_IDENTIFICATION_OTHERS,
		IDENTIFICATION_NBR = s.IDENTIFICATION_NBR,
		COUNTRY_OF_ISSUE = s.COUNTRY_OF_ISSUE,
		COUNTRY_OF_ISSUE_OTHERS = s.COUNTRY_OF_ISSUE_OTHERS,
		ISSUING_AUTHORITY = s.ISSUING_AUTHORITY,
		DATE_ISSUED = cast(s.DATE_ISSUED as date),
		DATE_EXPIRED = cast(s.DATE_EXPIRED as date),
		RESIDENTIAL_PERMIT_NBR = s.RESIDENTIAL_PERMIT_NBR,
		LAST_MODIFIED_DATE = GETDATE(),
		LAST_MODIFIED_USER = @caller
	when not matched then insert (
		CPF_CPP_REF_NBR,
		CPF_PPCT_TYPE_CODE,
		MEANS_OF_IDENTIFICATION,
		MEANS_OF_IDENTIFICATION_OTHERS,
		IDENTIFICATION_NBR,
		COUNTRY_OF_ISSUE,
		COUNTRY_OF_ISSUE_OTHERS,
		ISSUING_AUTHORITY,
		DATE_ISSUED,
		DATE_EXPIRED,
		RESIDENTIAL_PERMIT_NBR,
		CREATE_DATE,
		CREATE_USER,
		LAST_MODIFIED_DATE,
		LAST_MODIFIED_USER
	)
	values (
		s.CPF_CPP_REF_NBR,
		s.CPF_PPCT_TYPE_CODE,
		s.MEANS_OF_IDENTIFICATION,
		s.MEANS_OF_IDENTIFICATION_OTHERS,
		s.IDENTIFICATION_NBR,
		s.COUNTRY_OF_ISSUE,
		s.COUNTRY_OF_ISSUE_OTHERS,
		s.ISSUING_AUTHORITY,
		cast(s.DATE_ISSUED as date),
		cast(s.DATE_EXPIRED as date),
		s.RESIDENTIAL_PERMIT_NBR,
		getdate(),
		@caller,
		getdate(),
		@caller
	);
end

GO

