CREATE PROCEDURE [dbo].[SaveUploadedExcelRecord]
	@TQ_TRAN_NBR VARCHAR(50),
	@POLICY_NO VARCHAR(50),
	@AGN_SHT_DESC VARCHAR(50),
	@PROD_NAME VARCHAR(150),
	@RECEIPT_NO VARCHAR(50),
	@RECEIPT_DATE VARCHAR(50),
	@RECEIPT_TQ_DATE VARCHAR(50),
	@INSTALLMENT_AMT NUMERIC(18,2),
	@DEPOSIT_AMT NUMERIC(18,2),
	@ALLOCATED_AMT NUMERIC(18,2),
	@COMM_RATE_PCT FLOAT,
	@COMM_AMT NUMERIC(18,2),
	@WTH_TAX_RATE_PCT FLOAT,
	@WHT_AMT NUMERIC(18,2),
	@NET_COMM NUMERIC(18,2),
	@DR_CR_IND VARCHAR(1),
	@SRC VARCHAR(50)
AS
BEGIN
	insert into dbo.TQ_UPLOAD_DATA (
		TQ_TRAN_NBR,
		POLICY_NO,
		AGN_SHT_DESC,
		PROD_NAME,
		RECEIPT_NO,
		RECEIPT_DATE,
		RECEIPT_TQ_DATE,
		INSTALLMENT_AMT,
		DEPOSIT_AMT,
		ALLOCATED_AMT,
		COMM_RATE_PCT,
		COMM_AMT,
		WTH_TAX_RATE_PCT,
		WHT_AMT,
		NET_COMM,
		DR_CR_IND,
		SRC
	)
	values (
		@TQ_TRAN_NBR,
		@POLICY_NO,
		@AGN_SHT_DESC,
		@PROD_NAME,
		@RECEIPT_NO,
		@RECEIPT_DATE,
		@RECEIPT_TQ_DATE,
		@INSTALLMENT_AMT,
		@DEPOSIT_AMT,
		@ALLOCATED_AMT,
		@COMM_RATE_PCT,
		@COMM_AMT,
		@WTH_TAX_RATE_PCT,
		@WHT_AMT,
		@NET_COMM,
		@DR_CR_IND,
		@SRC
	)
END

GO

